version: '3.8'

services:
  server-bridge:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - API_KEY=your-super-secret-api-key-123
      - SERVERS_PATH=/app/servers
    volumes:
      - servers_data:/app/servers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  servers_data: